# Generated by Django 5.0.3 on 2024-03-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='position',
            field=models.CharField(default=None, max_length=200, verbose_name='Должность'),
        ),
    ]
