# Generated by Django 5.0.3 on 2024-03-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doctors', '0004_delete_doctors_doctor_groups_doctor_user_permissions'),
        ('pacients', '0003_alter_therapeuticanddiagnosticevents_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Doctors',
        ),
    ]
