# Generated by Django 5.0.3 on 2024-03-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctors_birthday_alter_doctors_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='position',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Должность'),
        ),
    ]
