# Generated by Django 5.0.3 on 2024-03-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctors_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'врач', 'verbose_name_plural': 'Врачи'},
        ),
    ]
