# Generated by Django 5.0.3 on 2024-03-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pacients/%Y/%Y/%m/%d/%H-%M-%S/', verbose_name='Фото')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения пациента')),
                ('series_passport', models.IntegerField(verbose_name='Серия паспорта')),
                ('numner_passport', models.IntegerField(verbose_name='Номер паспорта')),
                ('sex', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('state', models.CharField(help_text='Край, область', max_length=150, verbose_name='Субъект')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица')),
                ('house', models.CharField(max_length=20, verbose_name='Дом')),
                ('entrance', models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд')),
                ('apartment', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('medical_record_number', models.CharField(max_length=100, verbose_name='Номер медицинской карты')),
                ('date_created_medical_record', models.DateField(verbose_name='Дата выдачи медицинской карты пациента')),
            ],
            options={
                'verbose_name': 'пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='TherapeuticAndDiagnosticEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('started_date', models.DateTimeField(verbose_name='Дата и время приема')),
                ('ended_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания приема')),
                ('type', models.CharField(choices=[('лабораторное исследование', 'Лабораторное исследование'), ('инструментальная диагностика', 'Инструментальная диагностика'), ('лекарственная терапия', 'Лекарственная терапия'), ('физиотерапия', 'Физиотерапия'), ('хирургическое лечение', 'Хирургическое лечение')], max_length=150, verbose_name='Тип мероприятия')),
                ('event_name', models.CharField(max_length=200, verbose_name='Название проведенного мероприятия')),
                ('event_result', models.TextField(verbose_name='Результаты мероприятия')),
                ('diagnos', models.CharField(max_length=150, verbose_name='Диагнос')),
                ('recomendations', models.TextField(verbose_name='Рекомендации по дальнейшему лечению или контрольным исследованиям')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.doctors')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacients.pacients')),
            ],
            options={
                'verbose_name': 'лечебно-диагностическое  мероприятие',
                'verbose_name_plural': 'Лечебно-диагностические  мероприятия',
            },
        ),
    ]
