# Generated by Django 5.0.3 on 2024-04-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0004_pacients_insurance_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacients',
            name='issued_code_passport',
            field=models.CharField(default='000-000', max_length=7, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='pacients',
            name='issued_date_passport',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='pacients',
            name='issued_passport',
            field=models.CharField(max_length=200, null=True, verbose_name='Выдан'),
        ),
    ]
