# Generated by Django 5.0.3 on 2024-04-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0005_pacients_issued_code_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacients',
            name='contract_doc',
            field=models.FileField(null=True, upload_to='pacients/docs/contract/%Y/%m/%d/%H-%M-%S/', verbose_name='Договор на оказание медицинских услуг'),
        ),
        migrations.AddField(
            model_name='pacients',
            name='personal_data_doc',
            field=models.FileField(null=True, upload_to='pacients/docs/personal_data/%Y/%m/%d/%H-%M-%S/', verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
